name: ezfastnow
description: A Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

#  cupertino_icons: ^1.0.0
  cupertino_icons: ^1.0.2
  mvc_pattern: 6.1.3+2
  shared_preferences: 2.0.4
#  shared_preferences: 0.5.8
#  location: 3.0.2
#  url_launcher: 5.5.0
  url_launcher: 6.0.2
#  firebase_messaging: 6.0.16
#  cached_network_image: 2.2.0+1
  fluttertoast: 4.0.0
  intl_utils: 2.1.0
#  intl_utils: 1.6.3
#  firebase_auth: ^0.15.2
#  cloud_firestore: ^0.13.0+1
  sqflite: ^1.3.2+1
#  image_picker: ^0.6.0+17
#  firebase_storage: ^3.0.3
#  flutter_local_notifications: ^3.0.1+3
#  smooth_page_indicator: 0.2.1
#  flutter_picker: 1.1.5

  cloud_firestore: ^1.0.1
  firebase_core: ^1.0.1
#  firebase_core: ^0.5.0
  firebase_auth: ^1.0.1
#  firebase_auth: ^0.18.0+1
  google_sign_in: ^4.5.3
  firebase_core_platform_interface: ^4.0.0
  circular_countdown_timer: 0.1.0
  flutter_datetime_picker: 1.5.0
#  syncfusion_flutter_calendar: any
  syncfusion_flutter_calendar: 18.4.49
  toggle_switch: 0.1.9
  percent_indicator: 3.0.1
  fl_chart: ^0.30.0
  flutter_webview_plugin: ^0.3.0+2
  cached_network_image: 2.3.3
  firebase_messaging: 9.1.2
#  flutter_local_notifications: 5.0.0+1



#  cupertino_icons: ^1.0.0
#    mvc_pattern: 6.1.3+2
#    shared_preferences: 0.5.8
#    location: 3.0.2
#    url_launcher: 5.5.0
#    firebase_messaging: 6.0.16
#    cached_network_image: 2.2.0+1
#    fluttertoast: 4.0.0
#    intl_utils: 1.6.3
#    firebase_auth: ^0.15.2
#    cloud_firestore: ^0.13.0+1
#    sqflite: ^1.3.2+1
#    image_picker: ^0.6.0+17
#    firebase_storage: ^3.0.3
#    flutter_local_notifications: ^3.0.1+3

#  jiffy: 4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/img/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/rubik_regular.ttf
          weight: 100
        - asset: assets/fonts/rubik_regular.ttf
          weight: 200
        - asset: assets/fonts/rubik_regular.ttf
          weight: 300
        - asset: assets/fonts/rubik_regular.ttf
          weight: 400
        - asset: assets/fonts/rubik_regular.ttf
          weight: 500
        - asset: assets/fonts/rubik_medium.ttf
          weight: 600
        - asset: assets/fonts/rubik_medium.ttf
          weight: 700
        - asset: assets/fonts/rubik_bold.ttf
          weight: 800
        - asset: assets/fonts/rubik_bold.ttf
          weight: 900

flutter_intl:
  enabled: true